### ISSUE TITLE
Feedback on branch feature/auth-service

### ISSUE THREAD

**Issue by d-fankhauser** [breuerfelix/instapy-gui#41] opened 2019-07-03 08:42 UTC
Hi guys - i was using the auth-service branch and here is some feedback:

Interface (gui.instapy.io):
- like_by_tags don't save the tags; After revisiting the template it's empty again?
- interact_user_followers got the same problem for the field usernames 
- there are some problems with the css style of the input field for usernames and tags. it only displays 10 chars

![image](https://user-images.githubusercontent.com/45788226/60576866-84257c00-9d7e-11e9-9479-e25cfc1ab539.png)
![image](https://user-images.githubusercontent.com/45788226/60577032-e2525f00-9d7e-11e9-8b6a-588b7683efde.png)

Client:
`
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-03 10:35:05] []  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

[0703/103521.521:INFO:CONSOLE(0)] "The resource https://www.instagram.com/graphql/query/?query_hash=xxx&variables=%7B%22fetch_media_count%22%3A0%2C%22fetch_suggested_count%22%3A30%2C%22ignore_cache%22%3Atrue%2C%22filter_followed_friends%22%3Atrue%2C%22seen_ids%22%3A%5B%5D%2C%22include_reel%22%3Atrue%7D was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-03 10:35:53] []  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "bot.py", line 158, in <module>
    getattr(session, job['functionName'])(**arguments)
  File "C:\Users\username\Documents\_Privat\services\env\lib\site-packages\instapy\instapy.py", line 1780, in like_by_tags
    tags = [tag.strip() for tag in tags]
TypeError: 'NoneType' object is not iterable

`

**Comment by breuerfelix** [comment] 2019-07-03 14:49
the problem is, after you entered a tag or username, you have to press tab or enter so the username / tag gets into the input field :) you will see what I mean when you do it !

the second error is because of this... I introduced the new input box but this night I knew that I forgot the error handling and I put it on my todo list :D I will make the error handling for this list box better !

but until then, press enter or tab in the box :) in the future I will do it like that, that it automatically adds the item if you only enter one item to the list when you press save. could be a way to help this out.

thanks for the feedback !

**Comment by d-fankhauser** [comment] 2019-07-04 14:40
oh sorry - my bad :D
Haven't noticed, that it's a plugin where you have to use tab.
Now it works like a charm.  

Just one thing: the console where you can start the service - please make it faster.. it's very slow and you can't scroll down to the bottom line

**Comment by breuerfelix** [comment] 2019-07-04 19:33
just added some error handling, and if you forget to press enter or tab, it will automatically add the remaining input when you press save :)

would be cool if you could test the new handling and tell me if you like it ! if not, tell me what could be better :P I can only improve if I get feedback like you already gave me !

also just close this issue if everything is working again :)

**Closed** 2019-07-05 09:37 UTC
