### ISSUE TITLE
Docker compose up hangs at downloading

### ISSUE THREAD

**Issue by matej2** [breuerfelix/instapy-gui#33] opened 2019-06-09 15:57 UTC
When i run `docker-compose up` it hangs at downloading mongo:

```
insta-gui> docker-compose up
Pulling mongo (mongo:latest)...
latest: Pulling from library/mongo
9ff7e2e5f967: Downloading [=================================================> ]  43.38MB/43.77MB
59856638ac9f: Download complete
6f317d6d954b: Download complete
a9dde5e2a643: Download complete
815c6aedc001: Download complete
8566b2594855: Download complete
01c9fe451980: Download complete
5c9e7bc12cea: Download complete
c64dd2c4159a: Download complete
c283cca25ace: Download complete
051b3304da4a: Download complete
ab4327c34933: Download complete
80003bc32b79: Download complete
```

Here is docker version output;

```
> docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24302
 Built: Fri Mar 23 08:31:36 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server: Docker Engine - Community
 Engine:
  Version:      18.09.5
  API version:  1.39 (minimum version 1.12)
  Go version:   go1.10.8
  Git commit:   e8ff056dbc
  Built:        Thu Apr 11 04:50:00 2019
  OS/Arch:      linux/amd64
  Experimental: false
```

Docker-compose version oputput: 

```
> docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24302
 Built: Fri Mar 23 08:31:36 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server: Docker Engine - Community
 Engine:
  Version:      18.09.5
  API version:  1.39 (minimum version 1.12)
  Go version:   go1.10.8
  Git commit:   e8ff056dbc
  Built:        Thu Apr 11 04:50:00 2019
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by breuerfelix** [comment] 2019-06-11 15:23
do you have enough space on your machine ?
can you check that ?

**Comment by matej2** [comment] 2019-06-12 07:08
Yes, i do have enough disk space

**Comment by matej2** [comment] 2019-06-12 07:15
i am using Docker Toolbox

**Comment by breuerfelix** [comment] 2019-06-13 09:42
could you run `docker pull mongo` in the console and show the output ?

**Comment by matej2** [comment] 2019-06-16 14:34
```
Warning: failed to get default registry endpoint from daemon (error during connect: Get https://192.168.99.100:2376/v1.37/info: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.). Using system default: https://index.docker.io/v1/
error during connect: Post https://192.168.99.100:2376/v1.37/images/create?fromImage=mongo&tag=latest: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Comment by breuerfelix** [comment] 2019-06-19 08:54
this will be fixed with v2 which I hope to release in 2-3 weeks because you don't have to use docker at all :)

**Comment by matej2** [comment] 2019-06-19 10:50
Great. Thanks for the info.

**Comment by matej2** [comment] 2019-06-20 12:39
How do you mean you wont dont have to use docker at all?

**Comment by breuerfelix** [comment] 2019-06-22 18:00
with docker right now, you host all the infrastructure needed for the gui. like the database, the services which lets you create your templates and stuff like that.

but with the new setup, all these services run on free / cheap cloud solutions, so only the bot runs on your machine. that's why you don't need docker anymore :)

**Comment by matej2** [comment] 2019-06-22 20:08
I dont understand.. So we will link out local bot with remote services, which are already set up and ready to use? Or we will have to set up this remote services? What are the limits of theese cloud solutions? In my opinion we should leave dockerfile if anyone wants to host gui locally

**Comment by breuerfelix** [comment] 2019-06-23 08:24
yes you link your local bot with the remote services which are already set up for everyone :)

the limits are, we have a limit of database since and a limit of computation power for the services.

BUT I will make a gui support tier on open collective so once we exceed this limit, or our services will be too slow, we can gather some monthly payments so I can rent bigger services :)

but what I have set up right now will be enough for allooott of users. lets see how far it will bring us.

if you wanna host everything locally, you can also do that! all the source code is still here in this repo and you just have to make slight changes in order to run the whole setup locally :) maybe I will also provide a one command for that :)

**Comment by matej2** [comment] 2019-06-23 10:04
I understand, but i believe there are people who would still like to run all services locally 😃. 

And you mentioned that theese cloud services are free / cheap. Note that there are usually strict terms of use for such services. We have to check if it is allowed to provide service for multiple users...

What will happen if this project wont be mantained in the future? Will these cloud services still be available?

**Comment by breuerfelix** [comment] 2019-06-25 06:21
of course I can see your concerns :) thats why you can also run it completely local ! it just needs some small adjustments to the docker-compose file and it would work like a charm :)

but this will be a topic for another month :D I wanna fix all bugs first so everything works fine.

the problem is that 95% of the instagram users never ever heard of the command line. thats why I wanna make a really simple setup :)

well the hosting services are maintained via open collective, so as long as people donate, these services will be with full power. and if nobody gonna donate they will be slower with free tier.

But right now I pay 7 bucks a month to host these services. thats not that much :D that will be always possible to maintain :)

**Comment by Zettt** [comment] 2019-07-02 05:26
I don't want that either. The entire reason InstaPy is so good is because it runs on a local machine without all the cloud nonsense. I'm in control of my data, and my data never leaves localhost. If I want to change something on the local installation, I can just move stuff around, and it's done. With a foreign cloud environment that cannot be done as easily–or at all–anymore. Especially in a case where it's set up automatically™ for me. I'd like to see how this change fans out but because I haven't seen it yet, and it seems to be such a big deal, I do wonder whether I'd be liking the change or not. The way it is right now, the change is just dumped on the users, and we're in a take it or leave it kind of situation, and I'm not as excited as you Felix.

**Comment by breuerfelix** [comment] 2019-07-02 10:41
well instapy still runs on your local machine :)

the entire cloud platform is in this repository so if you don't wanna use the cloud infrastructure, you can just docker-compose up and spin up your own 'cloud' and connect your own 'cloud' with you instapy client :)

so this setup is made for advanced users who are comfortable using docker, they can do everything on their own because I don't hide any code (only the secrets but you can set your own) but its also good for people how want a double click up and running instapy gui :)

its hard to serve both group of users. some people want full control, some people want fast up and and running with no problems.

so this is why I try to make every group happy. you can check it out when its done, if its nothing for you, thats okay :) I can't make everybody happy :D just try to get most people happy as I can :D

**Comment by Zettt** [comment] 2019-07-03 09:09
I can totally see that Felix. I'm skeptical because I'm German, and I don't buy much of the cloud stuff that we have right now. I feel like InstaPy is for advanced users anyway, so I can't see why we'd need to move away from a local thing to something that is less strictly local. I just don't see the second user group you're mentioning -- if they exist, they're probably less than 10%. Anyway, as I said I'm skeptical but I'm awaiting the new release because right now there is nothing to look at. There's no new code added to this repository. Or am I missing something? That's why I said it's a hit or miss thing. 

For me personally I'm looking for ways to setup a bunch of Instagram accounts for customers. With the recent bot sweep on Instagram, I have to reconsider whether, and how, I can offer services to clients. InstaPy is my favorite because it's a lot more nerdy than say Combin or Jarvee. I welcome the work you do on the GUI, but if I can't do what I'd like to be doing, well, you can imagine, hopefully.

**Comment by breuerfelix** [comment] 2019-07-03 14:29
well I am alot in discord and ... there are many users trying to get started with instapy and they are not able to :D

but the main reason why I made this GUI is for better template and user handling. The goal is that you can create many Quickstart scripts and choose which one to start, and import scripts from other users :)

I guess that the cloud version could be something for your business because you can connect many bot clients to one instapy.io account (or your personal cloud) then you can create many different templates and many different 'global' settings. global settings consist of proxy, instagram credentials, and things like headless / bypass mobile etc.

on the start panel you can now choose your template, your bot client and your global settings via dropdown and hit start. you can then switch to another bot Client and start it with other settings and templates (scheduler would be awesome in the future... but I need time for that :D)

I don't wanna advertise the new version right here, just wanna mention it pros and why I made this change. Right now I am implementing the global settings handling. Hope this will be done till next week. But its up to you, try it out and you will see if it fits for you.

Its a nice project for my portfolio and I hope that I can help some people with it :D

**Closed** 2019-07-11 13:45 UTC
